dist: bionic
warnings_are_errors: false
os: linux

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - boost1.67
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev

services:
  - mysql

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mysql -uroot -e 'create database test_mysql;'
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=1 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install -DWITH_CPR=1
  - cd ..
  - chmod +x contrib/check_updates.sh

script:
  - $CXX --version
  - mysql -uroot < sql/create/create_mysql.sql
  - mysql -utrinity -ptrinity auth < sql/base/auth_database.sql
  - mysql -utrinity -ptrinity characters < sql/base/characters_database.sql
  - mysql -utrinity -ptrinity world < sql/base/dev/world_database.sql
  - mysql -utrinity -ptrinity hotfixes < sql/base/dev/hotfixes_database.sql
  - cat sql/ashamane/world/master/*.sql | mysql -utrinity -ptrinity world
  - cat sql/ashamane/hotfixes/master/*.sql | mysql -utrinity -ptrinity hotfixes
  - mysql -uroot < sql/create/drop_mysql.sql
  - cd bin
  - make -j 4 -k && make install
  - cd check_install/bin
  - ./bnetserver --version
  - ./worldserver --version
