DELETE FROM `creature_template_scaling` WHERE `Entry`=16294;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16294, 9, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15652;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15652, 8, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16196;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16196, 11, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15638;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15638, 5, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15967;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15967, 9, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15420;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15420, 7, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15641;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15641, 12, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15651;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15651, 6, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15643;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15643, 10, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15657;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15657, 7, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15670;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15670, 7, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=17849;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (17849, 5, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15645;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15645, 7, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15644;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15644, 5, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15958;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15958, 8, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15969;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15969, 12, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15407;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15407, 13, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15636;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15636, 8, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15656;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15656, 7, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15658;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15658, 8, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16183;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16183, 11, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15924;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15924, 12, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15945;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15945, 6, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15402;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15402, 8, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15941;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15941, 6, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15648;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15648, 6, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15647;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15647, 5, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15966;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15966, 9, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15937;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15937, 9, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15655;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15655, 7, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15668;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15668, 8, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15965;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15965, 12, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15669;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15669, 7, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16263;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16263, 9, 16, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15642;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15642, 10, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15950;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15950, 6, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15637;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15637, 8, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15968;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15968, 6, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15408;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15408, 12, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15949;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15949, 5, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16924;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16924, 5, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15650;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15650, 7, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15409;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15409, 10, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=19456;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (19456, 10, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=15649;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (15649, 5, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=17086;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (17086, 9, 21, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16443;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16443, 9, 20, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16315;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16315, 19, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=17210;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (17210, 22, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16357;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16357, 14, 62, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16198;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16198, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16464;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16464, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16339;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16339, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16197;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16197, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16304;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16304, 17, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16320;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16320, 22, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16231;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16231, 18, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16329;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16329, 25, 62, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16331;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16331, 20, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16318;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16318, 18, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16246;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16246, 19, 62, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16542;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16542, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16314;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16314, 20, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16322;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16322, 17, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16309;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16309, 17, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16325;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16325, 17, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16311;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16311, 14, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16323;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16323, 19, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16348;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16348, 10, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16201;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16201, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16326;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16326, 17, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16334;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16334, 17, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16402;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16402, 12, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16352;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16352, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16220;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16220, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=17656;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (17656, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16341;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16341, 11, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16252;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16252, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16301;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16301, 14, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16332;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16332, 20, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16358;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16358, 19, 62, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16344;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16344, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16293;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16293, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16480;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16480, 18, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16245;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16245, 19, 62, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16199;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16199, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16204;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16204, 21, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16239;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16239, 20, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16291;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16291, 21, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16237;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16237, 21, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16205;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16205, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16310;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16310, 17, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16253;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16253, 14, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16250;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16250, 23, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16342;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16342, 14, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16238;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16238, 24, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16274;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16274, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16353;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16353, 10, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16313;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16313, 10, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16319;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16319, 21, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16355;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16355, 17, 59, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16343;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16343, 15, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16665;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16665, 15, 24, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16345;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16345, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16328;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16328, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16224;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16224, 11, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16327;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16327, 11, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16337;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16337, 12, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16469;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16469, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16340;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16340, 10, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16302;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16302, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=17655;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (17655, 15, 22, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16305;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16305, 18, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16303;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16303, 11, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16403;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16403, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16351;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16351, 17, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16350;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16350, 11, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16330;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16330, 17, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16333;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16333, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16316;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16316, 19, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16324;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16324, 19, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16601;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16601, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16335;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16335, 18, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16200;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16200, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16317;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16317, 21, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16354;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16354, 13, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16346;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16346, 13, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16347;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16347, 10, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16528;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16528, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16462;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16462, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16213;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16213, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16295;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16295, 15, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16219;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16219, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16203;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16203, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16321;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16321, 22, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16202;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16202, 12, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16463;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16463, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16308;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16308, 19, 61, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16300;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16300, 20, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16349;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16349, 16, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16292;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16292, 13, 60, 0, 2, NULL);
DELETE FROM `creature_template_scaling` WHERE `Entry`=16162;
INSERT INTO `creature_template_scaling` (`Entry`, `LevelScalingMin`, `LevelScalingMax`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `VerifiedBuild`) VALUES (16162, 6, 20, 0, 2, NULL);

-- Orb of Translocation SAI
SET @ENTRY := 180911;
UPDATE `gameobject_template` SET `AIName`="SmartGameObjectAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,1,0,0,64,0,100,0,0,0,0,0,62,530,0,0,0,0,0,7,0,0,0,9332.3,-7814.27,136.5,5.3,"Orb of Translocation - On Gossip Hello - Teleport"),
(@ENTRY,1,1,0,64,0,100,0,0,0,0,0,85,52096,0,0,0,0,0,7,0,0,0,0,0,0,0,"Orb of Translocation - On Gossip Hello - Invoker Cast 'Cosmetic Teleport Effect'");
-- Orb of Translocation SAI
SET @ENTRY := 180912;
UPDATE `gameobject_template` SET `AIName`="SmartGameObjectAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=1;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,1,0,0,64,0,100,0,0,0,0,0,62,530,0,0,0,0,0,7,0,0,0,9333.9,-7880.27,74.9,2.1,"Orb of Translocation - On Gossip Hello - Teleport"),
(@ENTRY,1,1,0,64,0,100,0,0,0,0,0,85,52096,0,0,0,0,0,7,0,0,0,0,0,0,0,"Orb of Translocation - On Gossip Hello - Invoker Cast 'Cosmetic Teleport Effect'");

update `quest_template` set `RewardChoiceItemID1` = 22783 where `id` = 9176;
update `quest_template` set `RewardChoiceItemID2` = 22784 where `id` = 9176;
update `quest_template` set `RewardChoiceItemQuantity1` = 1 where `id` = 9176;
update `quest_template` set `RewardChoiceItemQuantity2` = 1 where `id` = 9176;
