UPDATE gameobject_template SET name="Portal to Hellfire Peninsula" WHERE entry=195141;
UPDATE gameobject_template SET name="Gate" WHERE entry IN (212939,212940,212941,212942,237407,237408);
UPDATE gameobject_template SET name="Gunship Portal" WHERE entry=215766;
UPDATE gameobject_template SET name="Horde Gunship Portal Effects" WHERE entry=215767;
UPDATE gameobject_template SET name="Portal to Dalaran" WHERE entry=216350;
UPDATE gameobject_template SET name="Portal to Ruins of Ogudei" WHERE entry=216491;
UPDATE gameobject_template SET name="Portal to Ironforge" WHERE entry=239438;
UPDATE gameobject_template SET name="Portal to Sparkrocket Outpost" WHERE entry=216492;
UPDATE gameobject_template SET name="Portal Back" WHERE name="Portail de retour";
UPDATE gameobject_template SET name="Sunreaver Portal" WHERE entry IN (218460,218486);
UPDATE gameobject_template SET name="Portal to Dawnseeker Promontory" WHERE entry=218817;
UPDATE gameobject_template SET name="Portal to Vale of Eternal Blossoms" WHERE entry=223212;
UPDATE gameobject_template SET name="Demon Portal" WHERE entry=229189;
UPDATE gameobject_template SET name="Khadgar's Portal" WHERE entry IN (230872,230874);
UPDATE gameobject_template SET name="Portal to Orgrimmar" WHERE entry=230945;
UPDATE gameobject_template SET name="Portal to Overwatch Entrance" WHERE entry=232562;
UPDATE gameobject_template SET name="Portal to Overwatch Summit" WHERE entry=232581;
UPDATE gameobject_template SET name="Portal to Stormshield Stronghold" WHERE entry=233285;
UPDATE gameobject_template SET name="Spike Gate" WHERE entry=233816;
UPDATE gameobject_template SET name="Portal Marker" WHERE entry=233976;
UPDATE gameobject_template SET name="Stormwind Portal" WHERE entry=234025;
UPDATE gameobject_template SET name="Overgrown Outpost Portal" WHERE entry=234121;
UPDATE gameobject_template SET name="Portal to Stormwind" WHERE entry=235883;
UPDATE gameobject_template SET name="Portal to Talador" WHERE entry=236689;
UPDATE gameobject_template SET name="Deactivated Ogre Waygate" WHERE entry IN (236765,236774,236906,236910,236911,236912);
UPDATE gameobject_template SET name="Stormshield Stronghold Portal" WHERE entry=239421;
UPDATE gameobject_template SET name="Warspear Outpost Portal" WHERE entry=239422;
UPDATE gameobject_template SET name="Portal to Thunder Bluff" WHERE entry=239435;
UPDATE gameobject_template SET name="Portal to Undercity" WHERE entry=239436;
UPDATE gameobject_template SET name="Portal to Ironforge" WHERE entry=239438;
UPDATE gameobject_template SET name="Portal to Darnassus" WHERE entry=239439;
UPDATE gameobject_template SET name="Portal Base" WHERE entry=239807;
UPDATE gameobject_template SET name="Portal Device" WHERE entry=239812;
UPDATE gameobject_template SET name="Deactivated Ogre Waygate" WHERE entry=243762;
UPDATE gameobject_template SET name="Bench" WHERE name="Banc";
UPDATE gameobject_template SET name="Woodbench" WHERE name="Banc en bois";
UPDATE gameobject_template SET name="Campfire" WHERE name="Feu de camp";
UPDATE gameobject_template SET name="Anvil" WHERE name="Enclume";
UPDATE gameobject_template SET name="Cookpot" WHERE name="Marmite";
UPDATE gameobject_template SET name="Cookpot" WHERE name="Marmite";