INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('188801', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213253', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213250', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213251', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213248', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213255', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213256', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213254', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213249', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213257', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213257', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213252', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213249', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213254', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213256', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213255', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213248', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213251', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213250', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213253', '188801', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213257', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213252', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213249', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213254', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213256', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213255', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213248', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213251', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213250', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213253', '188802', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('213252', '188800', '0', '2.1');
INSERT INTO `world`.`skill_discovery_template` (`spellId`, `reqSpell`, `reqSkillValue`, `chance`) VALUES ('188802', '188801', '0', '2.1');
DELETE FROM `world`.`spell_loot_template` WHERE (`Entry` = '188800') and (`Item` = '128630');
DELETE FROM `world`.`spell_loot_template` WHERE (`Entry` = '188801') and (`Item` = '128630');
DELETE FROM `world`.`spell_loot_template` WHERE (`Entry` = '188802') and (`Item` = '128630');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188801', '8', '300008', '100', '0', '1', '0', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '1', '300001', '100', '0', '1', '0', '1', '1', 'plants');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188801', '137596', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188801', '137597', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188801', '137595', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '2', '300002', '100', '0', '1', '0', '1', '1', 'gems');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '5', '300005', '100', '0', '1', '0', '1', '1', 'pants');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '6', '300006', '100', '0', '1', '0', '1', '1', 'leather');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '7', '300007', '100', '0', '1', '0', '1', '1', 'ore');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '3', '300003', '100', '0', '1', '0', '1', '1', 'enchant');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188801', '4', '300004', '100', '0', '1', '0', '1', '1', 'cloth');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '7', '300007', '100', '0', '1', '0', '1', '1', 'ore');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '6', '300006', '100', '0', '1', '0', '1', '1', 'leather');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '5', '300005', '100', '0', '1', '0', '1', '1', 'pants');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '4', '300004', '100', '0', '1', '0', '1', '1', 'cloth');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '3', '300003', '100', '0', '1', '0', '1', '1', 'enchant');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '2', '300002', '100', '0', '1', '0', '1', '1', 'gems');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188800', '1', '300001', '100', '0', '1', '0', '1', '1', 'plants');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188800', '8', '300008', '100', '0', '1', '0', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188800', '137597', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188800', '137596', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188800', '137595', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '1', '300001', '100', '0', '1', '0', '1', '1', 'plants');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '2', '300002', '100', '0', '1', '0', '1', '1', 'gems');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '3', '300003', '100', '0', '1', '0', '1', '1', 'enchant');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '4', '300004', '100', '0', '1', '0', '1', '1', 'cloth');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188802', '8', '300008', '100', '0', '1', '0', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188802', '137596', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188802', '137597', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '5', '300005', '100', '0', '1', '0', '1', '1', 'pants');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '6', '300006', '100', '0', '1', '0', '1', '1', 'leather');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('188802', '7', '300007', '100', '0', '1', '0', '1', '1', 'ore');
INSERT INTO `world`.`spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('188802', '137595', '0', '0', '0', '1', '1', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300001', '128304', '0', '10', '0', '1', '0', '1', '10');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300001', '124105', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300001', '124103', '0', '10', '0', '1', '0', '1', '5');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300001', '124104', '0', '10', '0', '1', '0', '1', '5');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300001', '124102', '0', '10', '0', '1', '0', '1', '5');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300001', '124101', '0', '10', '0', '1', '0', '1', '5');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130176', '0', '4', '0', '1', '0', '1', '2');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130172', '0', '4', '0', '1', '0', '1', '2');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130177', '0', '4', '0', '1', '0', '1', '2');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130173', '0', '4', '0', '1', '0', '1', '2');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130175', '0', '4', '0', '1', '0', '1', '2');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130174', '0', '4', '0', '1', '0', '1', '2');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '129100', '0', '10', '0', '1', '0', '1', '10');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130183', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130181', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130182', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130179', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130180', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300002', '130178', '0', '10', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300003', '124440', '0', '10', '0', '1', '0', '1', '10');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300003', '124442', '0', '2', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('300004', '124437', '0', '10', '0', '1', '0', '1', '20', NULL);
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('300005', '139398', '0', '4', '0', '1', '0', '1', '1', NULL);
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('300005', '139395', '0', '4', '0', '1', '0', '1', '1', NULL);
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('300005', '139394', '0', '4', '0', '1', '0', '1', '1', NULL);
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('300005', '139392', '0', '4', '0', '1', '0', '1', '1', NULL);
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES ('300005', '139393', '0', '4', '0', '1', '0', '1', '1', NULL);
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300006', '124115', '0', '10', '0', '1', '0', '1', '10');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300006', '124113', '0', '10', '0', '1', '0', '1', '10');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300007', '123919', '0', '10', '0', '1', '0', '1', '10');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300007', '123918', '0', '10', '0', '1', '0', '1', '20');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300008', '139396', '0', '40', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300008', '139397', '0', '40', '0', '1', '0', '1', '1');
INSERT INTO `world`.`reference_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`) VALUES ('300008', '139399', '0', '40', '0', '1', '0', '1', '1');
